spring:
  application:
    name: mybatis-mapper
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3307/orders?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 9090

mybatis:
  mapper-locations: mybatis/mapper/*.xml

server:
  port: 8080
  servlet:
    context-path: /