spring:
  application:
    name: mybatis-mapper
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb;MODE=MySQL
    username: sa
    password: 

mybatis:
  mapper-locations: mybatis/mapper/*.xml

server:
  port: 8080
  servlet:
    context-path: /